AWSTemplateFormatVersion : 2010-09-09

Description : |
  My first IaaC 

Resources:
  Kitty:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      KeyName: Myfirstkey
      #LaunchTemplate:
      #  LaunchTemplateId: lt-0315931742a1af8b2
      #  Version: 1
      InstanceType: t2.micro
      SecurityGroups:
        - NGNiX-SSH+HTTP
      Tags:
        - Key : Name
          Value : MCANMCAN-FT
      UserData:
       Fn::Base64:
        !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo yum install git -y
          systemctl enable httpd 
          systemctl start httpd 
          git clone https://github.com/MCANMCAN/KittenCarousel-AWSCloudFormation.git
          cd KittenCarousel-AWSCloudFormation
          sudo rm -rf /var/www/html/index.html
          sudo cp ./static-web/* /var/www/html/
          sudo systemctl restart httpd
